In [1]:
import re
import string
import nltk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train = pd.read_csv("/home/adarsh/Documents/MACHINE LEARNING - PROJECTS/Data/Twitter_Analysis/train.csv")
test = pd.read_csv("/home/adarsh/Documents/MACHINE LEARNING - PROJECTS/Data/Twitter_Analysis/test.csv")

In [3]:
train

id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?😍😍😍😍😍ð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow  

[31962 rows x 3 columns]

In [4]:
test

id                                              tweet
0      31963  #studiolife #aislife #requires #passion #dedic...
1      31964   @user #white #supremacists want everyone to s...
2      31965  safe ways to heal your #acne!!    #altwaystohe...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd #bihday to my amazing, hilarious #nephew...
...      ...                                                ...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 2 columns]

In [5]:
train.shape

(31962, 3)

In [6]:
test.shape

(17197, 2)

In [7]:
#Downloading commonly used data sets
import nltk
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /home/adarsh/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /home/adarsh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/adarsh/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [8]:
# APPEND TEST DATA WITH TRAIN DATA

merged = train.append(test)
merged

id  label                                              tweet
0          1    0.0   @user when a father is dysfunctional and is s...
1          2    0.0  @user @user thanks for #lyft credit i can't us...
2          3    0.0                                bihday your majesty
3          4    0.0  #model   i love u take with u all the time in ...
4          5    0.0             factsguide: society now    #motivation
...      ...    ...                                                ...
17192  49155    NaN  thought factory: left-right polarisation! #tru...
17193  49156    NaN  feeling like a mermaid 😘 #hairflip #neverre...
17194  49157    NaN  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158    NaN  happy, at work conference: right mindset leads...
17196  49159    NaN  my   song "so glad" free download!  #shoegaze ...

[49159 rows x 3 columns]

## PREPROCESSING

In [9]:
# SEPERATING TWEETS FROM THE APPENDED DATAFRAME (MERGED)
# 'tweets' CONTAIN BOTH TRAIN AND TEST TWEETS

tweets = merged.tweet
tweets

0         @user when a father is dysfunctional and is s...
1        @user @user thanks for #lyft credit i can't us...
2                                      bihday your majesty
3        #model   i love u take with u all the time in ...
4                   factsguide: society now    #motivation
                               ...                        
17192    thought factory: left-right polarisation! #tru...
17193    feeling like a mermaid 😘 #hairflip #neverre...
17194    #hillary #campaigned today in #ohio((omg)) &am...
17195    happy, at work conference: right mindset leads...
17196    my   song "so glad" free download!  #shoegaze ...
Name: tweet, Length: 49159, dtype: object

## TOKENIZATION

In [10]:
# TOKENIZING 'tweets' DATA AND THEN JOINING THEM TOGETHER

from nltk import TweetTokenizer
from nltk.tokenize import word_tokenize
tk = TweetTokenizer()
tweets = tweets.apply(lambda x: tk.tokenize(x)).apply(lambda x: ' '.join(x))

In [11]:
tweets

0        @user when a father is dysfunctional and is so...
1        @user @user thanks for #lyft credit i can't us...
2                                      bihday your majesty
3        #model i love u take with u all the time in ur...
4                     factsguide : society now #motivation
                               ...                        
17192    thought factory : left-right polarisation ! #t...
17193    feeling like a mermaid ð Ÿ ˜ ˜ #hairflip #neve...
17194    #hillary #campaigned today in #ohio ( ( omg ) ...
17195    happy , at work conference : right mindset lea...
17196    my song " so glad " free download ! #shoegaze ...
Name: tweet, Length: 49159, dtype: object

## REMOVING PUNCTUATIONS

In [12]:
tweets = tweets.str.replace('[^a-zA-Z]+', ' ')
tweets

0         user when a father is dysfunctional and is so...
1         user user thanks for lyft credit i can t use ...
2                                      bihday your majesty
3           model i love u take with u all the time in ur 
4                        factsguide society now motivation
                               ...                        
17192    thought factory left right polarisation trump ...
17193    feeling like a mermaid hairflip neverready for...
17194     hillary campaigned today in ohio omg used wor...
17195    happy at work conference right mindset leads t...
17196    my song so glad free download shoegaze newmusi...
Name: tweet, Length: 49159, dtype: object

In [13]:
from nltk.tokenize import word_tokenize

In [14]:
tweets

0         user when a father is dysfunctional and is so...
1         user user thanks for lyft credit i can t use ...
2                                      bihday your majesty
3           model i love u take with u all the time in ur 
4                        factsguide society now motivation
                               ...                        
17192    thought factory left right polarisation trump ...
17193    feeling like a mermaid hairflip neverready for...
17194     hillary campaigned today in ohio omg used wor...
17195    happy at work conference right mindset leads t...
17196    my song so glad free download shoegaze newmusi...
Name: tweet, Length: 49159, dtype: object

## REMOVING SHORT WORDS

In [15]:
# REMOVING SMALL WORD FROM TWEETS (LENGTH <= 3)

tweets = tweets.apply(lambda x: ' '.join([w for w in word_tokenize(x) if len(w) > 3]))
tweets

0        user when father dysfunctional selfish drags k...
1        user user thanks lyft credit cause they offer ...
2                                      bihday your majesty
3                                model love take with time
4                            factsguide society motivation
                               ...                        
17192    thought factory left right polarisation trump ...
17193    feeling like mermaid hairflip neverready forma...
17194    hillary campaigned today ohio used words like ...
17195    happy work conference right mindset leads cult...
17196    song glad free download shoegaze newmusic newsong
Name: tweet, Length: 49159, dtype: object

## STEMMING

In [16]:
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('english')
tweets = tweets.apply(lambda x: [stemmer.stem(i.lower()) for i in tk.tokenize(x)]).apply(lambda x: ' '.join(x))

In [17]:
tweets

0        user when father dysfunct selfish drag kid int...
1        user user thank lyft credit caus they offer wh...
2                                      bihday your majesti
3                                model love take with time
4                                  factsguid societi motiv
                               ...                        
17192    thought factori left right polaris trump usele...
17193    feel like mermaid hairflip neverreadi formal w...
17194    hillari campaign today ohio use word like asse...
17195    happi work confer right mindset lead cultur de...
17196       song glad free download shoegaz newmus newsong
Name: tweet, Length: 49159, dtype: object

## REMOVING STOP WORDS

In [18]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
tweets = tweets.apply(lambda x: [i for i in word_tokenize(x) if i not in stop]).apply(lambda x: ' '.join(x))

In [19]:
tweets

0           user father dysfunct selfish drag kid dysfunct
1        user user thank lyft credit caus offer wheelch...
2                                           bihday majesti
3                                     model love take time
4                                  factsguid societi motiv
                               ...                        
17192    thought factori left right polaris trump usele...
17193    feel like mermaid hairflip neverreadi formal w...
17194    hillari campaign today ohio use word like asse...
17195    happi work confer right mindset lead cultur de...
17196       song glad free download shoegaz newmus newsong
Name: tweet, Length: 49159, dtype: object

In [20]:
# REPLACING EXISTING TWEET COLUMN IN MERGED DATA WITH THE PROCESSED 'tweets'

merged.tweet = tweets
merged

id  label                                              tweet
0          1    0.0     user father dysfunct selfish drag kid dysfunct
1          2    0.0  user user thank lyft credit caus offer wheelch...
2          3    0.0                                     bihday majesti
3          4    0.0                               model love take time
4          5    0.0                            factsguid societi motiv
...      ...    ...                                                ...
17192  49155    NaN  thought factori left right polaris trump usele...
17193  49156    NaN  feel like mermaid hairflip neverreadi formal w...
17194  49157    NaN  hillari campaign today ohio use word like asse...
17195  49158    NaN  happi work confer right mindset lead cultur de...
17196  49159    NaN     song glad free download shoegaz newmus newsong

[49159 rows x 3 columns]

In [21]:
#Seperating train data and test data from merged data using the .iloc with row limit as the shape of the train data (which we loaded in the beginning)
train_data = merged.iloc[:train.shape[0]]

In [22]:
test_data = merged.iloc[train.shape[0]:]

In [23]:
train_data

id  label                                              tweet
0          1    0.0     user father dysfunct selfish drag kid dysfunct
1          2    0.0  user user thank lyft credit caus offer wheelch...
2          3    0.0                                     bihday majesti
3          4    0.0                               model love take time
4          5    0.0                            factsguid societi motiv
...      ...    ...                                                ...
31957  31958    0.0                                         user youuu
31958  31959    0.0  nina turner airwav tri wrap mantl genuin hero ...
31959  31960    0.0                       listen song monday morn work
31960  31961    1.0           user sikh templ vandalis calgari condemn
31961  31962    0.0                                  thank user follow

[31962 rows x 3 columns]

In [24]:
test_data

id  label                                              tweet
0      31963    NaN  studiolif aislif requir passion dedic willpow ...
1      31964    NaN      user white supremacist want everyon bird movi
2      31965    NaN          safe way heal acn altwaystoh healthi heal
3      31966    NaN  curs child book reserv alreadi harrypott potte...
4      31967    NaN  bihday amaz hilari nephew ahmir uncl dave love...
...      ...    ...                                                ...
17192  49155    NaN  thought factori left right polaris trump usele...
17193  49156    NaN  feel like mermaid hairflip neverreadi formal w...
17194  49157    NaN  hillari campaign today ohio use word like asse...
17195  49158    NaN  happi work confer right mindset lead cultur de...
17196  49159    NaN     song glad free download shoegaz newmus newsong

[17197 rows x 3 columns]

In [25]:
train_data

id  label                                              tweet
0          1    0.0     user father dysfunct selfish drag kid dysfunct
1          2    0.0  user user thank lyft credit caus offer wheelch...
2          3    0.0                                     bihday majesti
3          4    0.0                               model love take time
4          5    0.0                            factsguid societi motiv
...      ...    ...                                                ...
31957  31958    0.0                                         user youuu
31958  31959    0.0  nina turner airwav tri wrap mantl genuin hero ...
31959  31960    0.0                       listen song monday morn work
31960  31961    1.0           user sikh templ vandalis calgari condemn
31961  31962    0.0                                  thank user follow

[31962 rows x 3 columns]

In [26]:
# SEPERATING TWEETS FROM BOTH train_data and test_data

train_tweet = train_data.tweet
test_tweet = test_data.tweet

In [27]:
train_tweet

0           user father dysfunct selfish drag kid dysfunct
1        user user thank lyft credit caus offer wheelch...
2                                           bihday majesti
3                                     model love take time
4                                  factsguid societi motiv
                               ...                        
31957                                           user youuu
31958    nina turner airwav tri wrap mantl genuin hero ...
31959                         listen song monday morn work
31960             user sikh templ vandalis calgari condemn
31961                                    thank user follow
Name: tweet, Length: 31962, dtype: object

In [28]:
test_tweet

0        studiolif aislif requir passion dedic willpow ...
1            user white supremacist want everyon bird movi
2                safe way heal acn altwaystoh healthi heal
3        curs child book reserv alreadi harrypott potte...
4        bihday amaz hilari nephew ahmir uncl dave love...
                               ...                        
17192    thought factori left right polaris trump usele...
17193    feel like mermaid hairflip neverreadi formal w...
17194    hillari campaign today ohio use word like asse...
17195    happi work confer right mindset lead cultur de...
17196       song glad free download shoegaz newmus newsong
Name: tweet, Length: 17197, dtype: object

## TFIDF VECTORIZATION

In [29]:
# VECTORIZING THE TWEETS USING TFIDF VECTORIZER

from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer(stop_words = stop)

In [30]:
train_data_vec = vec.fit_transform(train_tweet)

In [31]:
test_data_vec = vec.transform(test_tweet)

In [32]:
train_data_vec

<31962x29414 sparse matrix of type '<class 'numpy.float64'>'
	with 213208 stored elements in Compressed Sparse Row format>

In [33]:
test_data_vec

<17197x29414 sparse matrix of type '<class 'numpy.float64'>'
	with 104348 stored elements in Compressed Sparse Row format>

In [34]:
# TAKING LABEL FROM train_data

y = train_data.label
y = y.values
y

array([0., 0., 0., ..., 0., 1., 0.])

In [35]:
# COUNTING LABEL VALUES 0 AND 1 TO CHECK THE IMBALANCE OF DATA

pd.Series(y).value_counts()

0.0    29720
1.0     2242
dtype: int64

## SPLITTING TRAIN AND TEST DATA

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_data_vec, y, test_size = 0.2, stratify = y, random_state = 42)

In [37]:
# TO OVERCOME THE IMBALANCED DATA

from imblearn.over_sampling import SMOTE
smote = SMOTE()
x_res, y_res = smote.fit_resample(x_train, y_train)

## RANDOM FOREST CLASSIFICATION

In [38]:
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier()
model2.fit(x_res, y_res)
y_pred2 = model2.predict(x_test)

In [39]:
y_pred2

array([0., 0., 0., ..., 0., 0., 0.])

In [40]:
y_test

array([0., 0., 0., ..., 0., 0., 0.])

In [41]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred2)

0.6891566265060242

## RF (SUBMISSION)

In [42]:
test_data_vec

<17197x29414 sparse matrix of type '<class 'numpy.float64'>'
	with 104348 stored elements in Compressed Sparse Row format>

In [43]:
y_sub2 = model2.predict(test_data_vec)

In [44]:
print(y_sub2)

[0. 1. 0. ... 0. 0. 0.]


In [45]:
my_submission = pd.DataFrame({'id': test.id, 'label': y_sub2})

In [46]:
my_submission.to_csv('submission_RF3.csv', index = False)